### ISSUE TITLE
jobs get stuck in inactive/failed state

### ISSUE THREAD

**Issue by ghost** [lykmapipo/sails-hook-subscriber#2]
I have a worker that extracts links from a web page- not sure why but this particular worker (unlike 4 which are working fine) either
a) gets stuck in inactive state
b) fail
one of the things is that this does not always happen which each of the jobs this worker finishes, so that's where the confusion is

Here's the code for the above mentioned worker: http://pastebin.com/xGhPcBt9

What i want to learn is:
a) how do i debug what's going wrong
b) what can i do to restart the job it fails - would use .attempt(x) be the best option?
c) how do i get the jobs to force continue if it gets stuck in inactive mode and nothing is really happening, atm what i have to do is restart the sails server after which the inactive jobs start processing but after some gets done, again the queue gets hanged

thanks :D

**Comment by lykmapipo** [comment]
@codefullon 

Whats the name of file you use to save your job?

**Comment by ghost** [comment]
hi @lykmapipo , the name of the worker file is 'LinksExtractWorker.js'

and below is the publisher code i use to save the job:

 var linksExtractJob = publisher.create('linksextract', {
            title: "grabbing links from the following url: " + urlPath,
            url: urlPath,
            urlId: urlId
}).save();

**Comment by lykmapipo** [comment]
@codefullon 

Thanks.

Am on it.

**Comment by ghost** [comment]
thanks a tonne @lykmapipo - excited to hear the solution :-)
cheers

**Comment by lykmapipo** [comment]
@codefullon 

The best way to debug is first to test your workers `perform` and make sure it pass all it specification.

On other hand,
- how do i debug what's going wrong
  In [kue error handling section](https://github.com/Automattic/kue#error-handling) explains a lot on how to deal with errors and stucked jobs.
-  what can i do to restart the job it fails - would use .attempt(x) be the best option?
  Based on [kue failure attempts usage](https://github.com/Automattic/kue#failure-attempts) its a best options to go with. But this has to go hand on hand with your requirements.
-  how do i get the jobs to force continue if it gets stuck in inactive mode and nothing is really happening
  By make use of [kue failure back off](https://github.com/Automattic/kue#failure-backoff) and [kue job ttl](https://github.com/Automattic/kue#job-ttl) you can prevent job from stucked in active state.

Hope it helps.

**Comment by lykmapipo** [comment]
@codefullon 

v1.0.0 fix this issue by upgrade to kue v0.9.4 and you have to utilize [job ttl](https://github.com/Automattic/kue#job-ttl)
