### ISSUE TITLE
Is there any way to access the Kue UI?

### ISSUE THREAD

**Issue by ronenteva** [lykmapipo/sails-hook-subscriber#4]

**Comment by lykmapipo** [comment]
@ronenteva 

No.current sails-hook-subscriber have not attach kue ui into sails.

But it seems to be good features if it will be available.Am open for discussion

**Comment by slavaparfenov** [comment]
@ronenteva

Add these lines into your `config/http.js`

```
  customMiddleware: function (app) {
    var kue = require('kue')
    var ui = require('kue-ui')

    ui.setup({
      apiURL: '/api',
      baseURL: '/kue',
      updateInterval: 5000
    })

    app.use('/api', kue.app)
    app.use('/kue', ui.app)
  },
```

Kue UI will be accessable at `/kue` URL.

**Comment by lykmapipo** [comment]
@slavaparfenov 

Thanks for the fix updates.
